text_preprocessor:
  # NLTK downloads needed: punkt, stopwords, wordnet
  remove_stopwords: true
  lemmatize: true
  min_token_length: 2


feature_builder:

  tfidf:
    max_features: 30000
    ngram_range: [1,2]
    min_df: 2
    max_df: 0.95

  transformer:
    model_name: distilbert-base-uncased
    max_length: 256


data_transformation:
  test_size: 0.30
  validation_size: 0.50
  random_state: 42


random_search:
  n_iter: 10 #20
  cv: 3 #5
  scoring: "f1_macro"
  random_state: 42
  n_jobs: -1
  verbose: 2


logistic_regression:
  C: [0.01, 0.1, 1, 10, 100]
  penalty: ["l2"]
  solver: ["lbfgs"]
  max_iter: [1000]
  class_weight: [null]


multinomial_naive_bayes:
  alpha: [0.01, 0.1, 0.5, 1.0]
  fit_prior: [true, false]


linear_svm:
  C: [0.01, 0.1, 1, 10]
  loss: ["hinge", "squared_hinge"]
  max_iter: [10000]
  class_weight: [null]


lightgbm:
  n_estimators: [100, 200]
  learning_rate: [0.01, 0.05, 0.1]
  num_leaves: [31, 63]
  max_depth: [-1, 10]
  feature_fraction: [0.8, 1.0]
  bagging_fraction: [0.8, 1.0]

  min_child_samples:
  - 20
  - 40

  lambda_l1:
  - 0
  - 0.1

  lambda_l2:
  - 0
  - 1